#!/bin/bash

mkdir -p /etc/qcollect/
cat /opt/qnib/qcollect/etc/qcollect.conf \
  |sed -e "s/QCOLLECT_PREFIX/${QCOLLECT_PREFIX}/" \
       -e "s/QCOLLECT_INTERVAL/${QCOLLECT_INTERVAL}/" \
       -e "s/QCOLLECT_PORT/${QCOLLECT_PORT}/" \
       -e "s/QCOLLECT_INTERNAL_SERVER_PORT/${QCOLLECT_INTERNAL_SERVER_PORT}/" \
       -e "s/QCOLLECT_HOSTNAME/${QCOLLECT_HOSTNAME}/" \
       -e "s/QCOLLECT_GRAPHITE_SERVER/${QCOLLECT_GRAPHITE_SERVER}/" \
       -e "s/QCOLLECT_GRAPHITE_INTERVAL/${QCOLLECT_GRAPHITE_INTERVAL}/" \
       -e "s/QCOLLECT_GRAPHITE_PREFIX_DIMENSIONS/${QCOLLECT_GRAPHITE_PREFIX_DIMENSIONS}/" \
       -e "s/QCOLLECT_INFLUXDB_SERVER/${QCOLLECT_INFLUXDB_SERVER}/" \
       -e "s/QCOLLECT_INFLUXDB_PORT/${QCOLLECT_INFLUXDB_PORT}/" \
       -e "s/QCOLLECT_INFLUXDB_INTERVAL/${QCOLLECT_INFLUXDB_INTERVAL}/" \
       -e "s/QCOLLECT_INFLUXDB_USERNAME/${QCOLLECT_INFLUXDB_USERNAME}/" \
       -e "s/QCOLLECT_INFLUXDB_PASSWORD/${QCOLLECT_INFLUXDB_PASSWORD}/" \
       -e "s/QCOLLECT_INFLUXDB_DATABASE/${QCOLLECT_INFLUXDB_DATABASE}/" \
       -e "s/QCOLLECT_PREFIX/${QCOLLECT_PREFIX}/" \
       -e "s/QCOLLECT_PREFIX/${QCOLLECT_PREFIX}/" \
  > /etc/qcollect/qcollect.conf
